### ISSUE TITLE
/var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/subscriber.rb:73:in `add_subscription': Invalid suback packet id: 3 (PahoMqtt::PacketException)

### ISSUE THREAD

**Issue by rgaufman** [RubyDevInc/paho.mqtt.ruby#36]
Hi there,

I'm seeing this happen every few hours of running, I'm not quite sure why it's getting an invalid suback, but is there any way to make it handle this gracefully somehow with a warning instead of an exception?

It's strange because the sub only happens once at the beginning, so I'm not sure why it is getting a suback, hmm

```ruby
#<Thread:0x00007f79a008e078@/var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/client.rb:129 run> terminated with exception (report_on_exception is true):
/var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/subscriber.rb:73:in `add_subscription': Invalid suback packet id: 3 (PahoMqtt::PacketException)
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/handler.rb:127:in `handle_suback'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/handler.rb:57:in `handle_packet'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/handler.rb:47:in `receive_packet'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/client.rb:168:in `block in loop_read'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/client.rb:166:in `times'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/client.rb:166:in `loop_read'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/client.rb:180:in `mqtt_loop'
	from /var/lib/gems/2.5.0/gems/paho-mqtt-1.0.9/lib/paho_mqtt/client.rb:133:in `block in daemon_mode'
```

**Comment by p-goudet** [comment]
Um, I could notice the same kind of error. Thank you for this report, I will check that as soon as possible.

**Comment by p-goudet** [comment]
This error is usually raised when the client receive an unexpected SUBACK packet. The client could found the matching SUBSCRIBE packet to the SUBACK packet.  I could not reproduce this error recently, could you send me some samples to reproduce this?
